NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 13
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = 0.0
NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.0
NDefines.NCountry.BASE_RESEARCH_SLOTS = 3
